#!/bin/bash
# this posts whatever you pipe to it directly to sprunge
# and then copy the resulting link to your clipboard using xclip
SPRUNGELINK=$(curl -sF "sprunge=<-" http://sprunge.us)
echo $SPRUNGELINK | xclip -i  -selection clipboard
echo $SPRUNGELINK
